/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleId = IDL.Nat;
export const CreateJobRequest = IDL.Record({
  'title' : IDL.Text,
  'cost' : IDL.Nat,
  'description' : IDL.Text,
  'vehicleId' : VehicleId,
});
export const JobId = IDL.Nat;
export const JobStatus = IDL.Variant({
  'pending' : IDL.Null,
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Job = IDL.Record({
  'id' : JobId,
  'status' : JobStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'title' : IDL.Text,
  'cost' : IDL.Nat,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'vehicleId' : VehicleId,
});
export const CreateMaintenanceRequest = IDL.Record({
  'title' : IDL.Text,
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'vehicleId' : VehicleId,
});
export const MaintenanceId = IDL.Nat;
export const MaintenanceStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'overdue' : IDL.Null,
});
export const MaintenanceItem = IDL.Record({
  'id' : MaintenanceId,
  'status' : MaintenanceStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'title' : IDL.Text,
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'vehicleId' : VehicleId,
});
export const VehicleType = IDL.Variant({
  'auto' : IDL.Null,
  'moto' : IDL.Null,
});
export const CreateVehicleRequest = IDL.Record({
  'model' : IDL.Text,
  'vehicleType' : VehicleType,
  'licensePlate' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'brand' : IDL.Text,
});
export const Vehicle = IDL.Record({
  'id' : VehicleId,
  'model' : IDL.Text,
  'vehicleType' : VehicleType,
  'licensePlate' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'brand' : IDL.Text,
});
export const DashboardSummary = IDL.Record({
  'pendingJobsCount' : IDL.Nat,
  'totalExpenses' : IDL.Nat,
  'overdueMaintenanceCount' : IDL.Nat,
  'vehicleCount' : IDL.Nat,
});
export const UpdateJobRequest = IDL.Record({
  'status' : IDL.Opt(JobStatus),
  'completedAt' : IDL.Opt(Timestamp),
  'title' : IDL.Opt(IDL.Text),
  'cost' : IDL.Opt(IDL.Nat),
  'description' : IDL.Opt(IDL.Text),
});
export const UpdateMaintenanceRequest = IDL.Record({
  'status' : IDL.Opt(MaintenanceStatus),
  'completedAt' : IDL.Opt(Timestamp),
  'title' : IDL.Opt(IDL.Text),
  'dueDate' : IDL.Opt(Timestamp),
  'description' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addJob' : IDL.Func([CreateJobRequest], [Job], []),
  'addMaintenance' : IDL.Func(
      [CreateMaintenanceRequest],
      [MaintenanceItem],
      [],
    ),
  'addVehicle' : IDL.Func([CreateVehicleRequest], [Vehicle], []),
  'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
  'deleteMaintenance' : IDL.Func([MaintenanceId], [IDL.Bool], []),
  'deleteVehicle' : IDL.Func([VehicleId], [IDL.Bool], []),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'getMaintenance' : IDL.Func(
      [MaintenanceId],
      [IDL.Opt(MaintenanceItem)],
      ['query'],
    ),
  'getRecentJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getUpcomingOrOverdueMaintenance' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceItem)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([VehicleId], [IDL.Opt(Vehicle)], ['query']),
  'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'listMaintenance' : IDL.Func([], [IDL.Vec(MaintenanceItem)], ['query']),
  'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'updateJob' : IDL.Func([JobId, UpdateJobRequest], [IDL.Opt(Job)], []),
  'updateMaintenance' : IDL.Func(
      [MaintenanceId, UpdateMaintenanceRequest],
      [IDL.Opt(MaintenanceItem)],
      [],
    ),
  'updateVehicle' : IDL.Func(
      [VehicleId, CreateVehicleRequest],
      [IDL.Opt(Vehicle)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleId = IDL.Nat;
  const CreateJobRequest = IDL.Record({
    'title' : IDL.Text,
    'cost' : IDL.Nat,
    'description' : IDL.Text,
    'vehicleId' : VehicleId,
  });
  const JobId = IDL.Nat;
  const JobStatus = IDL.Variant({
    'pending' : IDL.Null,
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Job = IDL.Record({
    'id' : JobId,
    'status' : JobStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'title' : IDL.Text,
    'cost' : IDL.Nat,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'vehicleId' : VehicleId,
  });
  const CreateMaintenanceRequest = IDL.Record({
    'title' : IDL.Text,
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'vehicleId' : VehicleId,
  });
  const MaintenanceId = IDL.Nat;
  const MaintenanceStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const MaintenanceItem = IDL.Record({
    'id' : MaintenanceId,
    'status' : MaintenanceStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'title' : IDL.Text,
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'vehicleId' : VehicleId,
  });
  const VehicleType = IDL.Variant({ 'auto' : IDL.Null, 'moto' : IDL.Null });
  const CreateVehicleRequest = IDL.Record({
    'model' : IDL.Text,
    'vehicleType' : VehicleType,
    'licensePlate' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'brand' : IDL.Text,
  });
  const Vehicle = IDL.Record({
    'id' : VehicleId,
    'model' : IDL.Text,
    'vehicleType' : VehicleType,
    'licensePlate' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'brand' : IDL.Text,
  });
  const DashboardSummary = IDL.Record({
    'pendingJobsCount' : IDL.Nat,
    'totalExpenses' : IDL.Nat,
    'overdueMaintenanceCount' : IDL.Nat,
    'vehicleCount' : IDL.Nat,
  });
  const UpdateJobRequest = IDL.Record({
    'status' : IDL.Opt(JobStatus),
    'completedAt' : IDL.Opt(Timestamp),
    'title' : IDL.Opt(IDL.Text),
    'cost' : IDL.Opt(IDL.Nat),
    'description' : IDL.Opt(IDL.Text),
  });
  const UpdateMaintenanceRequest = IDL.Record({
    'status' : IDL.Opt(MaintenanceStatus),
    'completedAt' : IDL.Opt(Timestamp),
    'title' : IDL.Opt(IDL.Text),
    'dueDate' : IDL.Opt(Timestamp),
    'description' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addJob' : IDL.Func([CreateJobRequest], [Job], []),
    'addMaintenance' : IDL.Func(
        [CreateMaintenanceRequest],
        [MaintenanceItem],
        [],
      ),
    'addVehicle' : IDL.Func([CreateVehicleRequest], [Vehicle], []),
    'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
    'deleteMaintenance' : IDL.Func([MaintenanceId], [IDL.Bool], []),
    'deleteVehicle' : IDL.Func([VehicleId], [IDL.Bool], []),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'getMaintenance' : IDL.Func(
        [MaintenanceId],
        [IDL.Opt(MaintenanceItem)],
        ['query'],
      ),
    'getRecentJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getUpcomingOrOverdueMaintenance' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceItem)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([VehicleId], [IDL.Opt(Vehicle)], ['query']),
    'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'listMaintenance' : IDL.Func([], [IDL.Vec(MaintenanceItem)], ['query']),
    'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'updateJob' : IDL.Func([JobId, UpdateJobRequest], [IDL.Opt(Job)], []),
    'updateMaintenance' : IDL.Func(
        [MaintenanceId, UpdateMaintenanceRequest],
        [IDL.Opt(MaintenanceItem)],
        [],
      ),
    'updateVehicle' : IDL.Func(
        [VehicleId, CreateVehicleRequest],
        [IDL.Opt(Vehicle)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };