/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateJobRequest {
  'title' : string,
  'cost' : bigint,
  'description' : string,
  'vehicleId' : VehicleId,
}
export interface CreateMaintenanceRequest {
  'title' : string,
  'dueDate' : Timestamp,
  'description' : string,
  'vehicleId' : VehicleId,
}
export interface CreateVehicleRequest {
  'model' : string,
  'vehicleType' : VehicleType,
  'licensePlate' : string,
  'name' : string,
  'year' : bigint,
  'brand' : string,
}
export interface DashboardSummary {
  'pendingJobsCount' : bigint,
  'totalExpenses' : bigint,
  'overdueMaintenanceCount' : bigint,
  'vehicleCount' : bigint,
}
export interface Job {
  'id' : JobId,
  'status' : JobStatus,
  'completedAt' : [] | [Timestamp],
  'title' : string,
  'cost' : bigint,
  'createdAt' : Timestamp,
  'description' : string,
  'vehicleId' : VehicleId,
}
export type JobId = bigint;
export type JobStatus = { 'pending' : null } |
  { 'in_progress' : null } |
  { 'completed' : null };
export type MaintenanceId = bigint;
export interface MaintenanceItem {
  'id' : MaintenanceId,
  'status' : MaintenanceStatus,
  'completedAt' : [] | [Timestamp],
  'title' : string,
  'dueDate' : Timestamp,
  'description' : string,
  'vehicleId' : VehicleId,
}
export type MaintenanceStatus = { 'upcoming' : null } |
  { 'completed' : null } |
  { 'overdue' : null };
export type Timestamp = bigint;
export interface UpdateJobRequest {
  'status' : [] | [JobStatus],
  'completedAt' : [] | [Timestamp],
  'title' : [] | [string],
  'cost' : [] | [bigint],
  'description' : [] | [string],
}
export interface UpdateMaintenanceRequest {
  'status' : [] | [MaintenanceStatus],
  'completedAt' : [] | [Timestamp],
  'title' : [] | [string],
  'dueDate' : [] | [Timestamp],
  'description' : [] | [string],
}
export interface Vehicle {
  'id' : VehicleId,
  'model' : string,
  'vehicleType' : VehicleType,
  'licensePlate' : string,
  'name' : string,
  'year' : bigint,
  'brand' : string,
}
export type VehicleId = bigint;
export type VehicleType = { 'auto' : null } |
  { 'moto' : null };
export interface _SERVICE {
  'addJob' : ActorMethod<[CreateJobRequest], Job>,
  'addMaintenance' : ActorMethod<[CreateMaintenanceRequest], MaintenanceItem>,
  'addVehicle' : ActorMethod<[CreateVehicleRequest], Vehicle>,
  'deleteJob' : ActorMethod<[JobId], boolean>,
  'deleteMaintenance' : ActorMethod<[MaintenanceId], boolean>,
  'deleteVehicle' : ActorMethod<[VehicleId], boolean>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getJob' : ActorMethod<[JobId], [] | [Job]>,
  'getMaintenance' : ActorMethod<[MaintenanceId], [] | [MaintenanceItem]>,
  'getRecentJobs' : ActorMethod<[], Array<Job>>,
  'getUpcomingOrOverdueMaintenance' : ActorMethod<[], Array<MaintenanceItem>>,
  'getVehicle' : ActorMethod<[VehicleId], [] | [Vehicle]>,
  'listJobs' : ActorMethod<[], Array<Job>>,
  'listMaintenance' : ActorMethod<[], Array<MaintenanceItem>>,
  'listVehicles' : ActorMethod<[], Array<Vehicle>>,
  'updateJob' : ActorMethod<[JobId, UpdateJobRequest], [] | [Job]>,
  'updateMaintenance' : ActorMethod<
    [MaintenanceId, UpdateMaintenanceRequest],
    [] | [MaintenanceItem]
  >,
  'updateVehicle' : ActorMethod<
    [VehicleId, CreateVehicleRequest],
    [] | [Vehicle]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];