/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateVehicleRequest {
    model: string;
    vehicleType: VehicleType;
    licensePlate: string;
    name: string;
    year: bigint;
    brand: string;
}
export type Timestamp = bigint;
export type VehicleId = bigint;
export type MaintenanceId = bigint;
export interface CreateJobRequest {
    title: string;
    cost: bigint;
    description: string;
    vehicleId: VehicleId;
}
export type JobId = bigint;
export interface DashboardSummary {
    pendingJobsCount: bigint;
    totalExpenses: bigint;
    overdueMaintenanceCount: bigint;
    vehicleCount: bigint;
}
export interface Vehicle {
    id: VehicleId;
    model: string;
    vehicleType: VehicleType;
    licensePlate: string;
    name: string;
    year: bigint;
    brand: string;
}
export interface UpdateJobRequest {
    status?: JobStatus;
    completedAt?: Timestamp;
    title?: string;
    cost?: bigint;
    description?: string;
}
export interface Job {
    id: JobId;
    status: JobStatus;
    completedAt?: Timestamp;
    title: string;
    cost: bigint;
    createdAt: Timestamp;
    description: string;
    vehicleId: VehicleId;
}
export interface UpdateMaintenanceRequest {
    status?: MaintenanceStatus;
    completedAt?: Timestamp;
    title?: string;
    dueDate?: Timestamp;
    description?: string;
}
export interface CreateMaintenanceRequest {
    title: string;
    dueDate: Timestamp;
    description: string;
    vehicleId: VehicleId;
}
export interface MaintenanceItem {
    id: MaintenanceId;
    status: MaintenanceStatus;
    completedAt?: Timestamp;
    title: string;
    dueDate: Timestamp;
    description: string;
    vehicleId: VehicleId;
}
export enum JobStatus {
    pending = "pending",
    in_progress = "in_progress",
    completed = "completed"
}
export enum MaintenanceStatus {
    upcoming = "upcoming",
    completed = "completed",
    overdue = "overdue"
}
export enum VehicleType {
    auto = "auto",
    moto = "moto"
}
export interface backendInterface {
    addJob(req: CreateJobRequest): Promise<Job>;
    addMaintenance(req: CreateMaintenanceRequest): Promise<MaintenanceItem>;
    addVehicle(req: CreateVehicleRequest): Promise<Vehicle>;
    deleteJob(id: JobId): Promise<boolean>;
    deleteMaintenance(id: MaintenanceId): Promise<boolean>;
    deleteVehicle(id: VehicleId): Promise<boolean>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getJob(id: JobId): Promise<Job | null>;
    getMaintenance(id: MaintenanceId): Promise<MaintenanceItem | null>;
    getRecentJobs(): Promise<Array<Job>>;
    getUpcomingOrOverdueMaintenance(): Promise<Array<MaintenanceItem>>;
    getVehicle(id: VehicleId): Promise<Vehicle | null>;
    listJobs(): Promise<Array<Job>>;
    listMaintenance(): Promise<Array<MaintenanceItem>>;
    listVehicles(): Promise<Array<Vehicle>>;
    updateJob(id: JobId, req: UpdateJobRequest): Promise<Job | null>;
    updateMaintenance(id: MaintenanceId, req: UpdateMaintenanceRequest): Promise<MaintenanceItem | null>;
    updateVehicle(id: VehicleId, req: CreateVehicleRequest): Promise<Vehicle | null>;
}
import type { CreateVehicleRequest as _CreateVehicleRequest, Job as _Job, JobId as _JobId, JobStatus as _JobStatus, MaintenanceId as _MaintenanceId, MaintenanceItem as _MaintenanceItem, MaintenanceStatus as _MaintenanceStatus, Timestamp as _Timestamp, UpdateJobRequest as _UpdateJobRequest, UpdateMaintenanceRequest as _UpdateMaintenanceRequest, Vehicle as _Vehicle, VehicleId as _VehicleId, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addJob(arg0: CreateJobRequest): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(arg0);
                return from_candid_Job_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(arg0);
            return from_candid_Job_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addMaintenance(arg0: CreateMaintenanceRequest): Promise<MaintenanceItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaintenance(arg0);
                return from_candid_MaintenanceItem_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaintenance(arg0);
            return from_candid_MaintenanceItem_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async addVehicle(arg0: CreateVehicleRequest): Promise<Vehicle> {
        if (this.processError) {
            try {
                const result = await this.actor.addVehicle(to_candid_CreateVehicleRequest_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Vehicle_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVehicle(to_candid_CreateVehicleRequest_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Vehicle_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteJob(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteMaintenance(arg0: MaintenanceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaintenance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaintenance(arg0);
            return result;
        }
    }
    async deleteVehicle(arg0: VehicleId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVehicle(arg0);
            return result;
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getJob(arg0: JobId): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaintenance(arg0: MaintenanceId): Promise<MaintenanceItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenance(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenance(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentJobs();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentJobs();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingOrOverdueMaintenance(): Promise<Array<MaintenanceItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingOrOverdueMaintenance();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingOrOverdueMaintenance();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicle(arg0: VehicleId): Promise<Vehicle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicle(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicle(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async listJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMaintenance(): Promise<Array<MaintenanceItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMaintenance();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMaintenance();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVehicles();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVehicles();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateJob(arg0: JobId, arg1: UpdateJobRequest): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, to_candid_UpdateJobRequest_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, to_candid_UpdateJobRequest_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMaintenance(arg0: MaintenanceId, arg1: UpdateMaintenanceRequest): Promise<MaintenanceItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaintenance(arg0, to_candid_UpdateMaintenanceRequest_n28(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaintenance(arg0, to_candid_UpdateMaintenanceRequest_n28(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVehicle(arg0: VehicleId, arg1: CreateVehicleRequest): Promise<Vehicle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicle(arg0, to_candid_CreateVehicleRequest_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicle(arg0, to_candid_CreateVehicleRequest_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_JobStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_MaintenanceItem_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaintenanceItem): MaintenanceItem {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_MaintenanceStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaintenanceStatus): MaintenanceStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Vehicle_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Vehicle {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MaintenanceItem]): MaintenanceItem | null {
    return value.length === 0 ? null : from_candid_MaintenanceItem_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vehicle]): Vehicle | null {
    return value.length === 0 ? null : from_candid_Vehicle_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VehicleId;
    model: string;
    vehicleType: _VehicleType;
    licensePlate: string;
    name: string;
    year: bigint;
    brand: string;
}): {
    id: VehicleId;
    model: string;
    vehicleType: VehicleType;
    licensePlate: string;
    name: string;
    year: bigint;
    brand: string;
} {
    return {
        id: value.id,
        model: value.model,
        vehicleType: from_candid_VehicleType_n16(_uploadFile, _downloadFile, value.vehicleType),
        licensePlate: value.licensePlate,
        name: value.name,
        year: value.year,
        brand: value.brand
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    status: _JobStatus;
    completedAt: [] | [_Timestamp];
    title: string;
    cost: bigint;
    createdAt: _Timestamp;
    description: string;
    vehicleId: _VehicleId;
}): {
    id: JobId;
    status: JobStatus;
    completedAt?: Timestamp;
    title: string;
    cost: bigint;
    createdAt: Timestamp;
    description: string;
    vehicleId: VehicleId;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n3(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.completedAt)),
        title: value.title,
        cost: value.cost,
        createdAt: value.createdAt,
        description: value.description,
        vehicleId: value.vehicleId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MaintenanceId;
    status: _MaintenanceStatus;
    completedAt: [] | [_Timestamp];
    title: string;
    dueDate: _Timestamp;
    description: string;
    vehicleId: _VehicleId;
}): {
    id: MaintenanceId;
    status: MaintenanceStatus;
    completedAt?: Timestamp;
    title: string;
    dueDate: Timestamp;
    description: string;
    vehicleId: VehicleId;
} {
    return {
        id: value.id,
        status: from_candid_MaintenanceStatus_n8(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.completedAt)),
        title: value.title,
        dueDate: value.dueDate,
        description: value.description,
        vehicleId: value.vehicleId
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    auto: null;
} | {
    moto: null;
}): VehicleType {
    return "auto" in value ? VehicleType.auto : "moto" in value ? VehicleType.moto : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    in_progress: null;
} | {
    completed: null;
}): JobStatus {
    return "pending" in value ? JobStatus.pending : "in_progress" in value ? JobStatus.in_progress : "completed" in value ? JobStatus.completed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    completed: null;
} | {
    overdue: null;
}): MaintenanceStatus {
    return "upcoming" in value ? MaintenanceStatus.upcoming : "completed" in value ? MaintenanceStatus.completed : "overdue" in value ? MaintenanceStatus.overdue : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MaintenanceItem>): Array<MaintenanceItem> {
    return value.map((x)=>from_candid_MaintenanceItem_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vehicle>): Array<Vehicle> {
    return value.map((x)=>from_candid_Vehicle_n14(_uploadFile, _downloadFile, x));
}
function to_candid_CreateVehicleRequest_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateVehicleRequest): _CreateVehicleRequest {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_MaintenanceStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaintenanceStatus): _MaintenanceStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateJobRequest_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateJobRequest): _UpdateJobRequest {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateMaintenanceRequest_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateMaintenanceRequest): _UpdateMaintenanceRequest {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: string;
    vehicleType: VehicleType;
    licensePlate: string;
    name: string;
    year: bigint;
    brand: string;
}): {
    model: string;
    vehicleType: _VehicleType;
    licensePlate: string;
    name: string;
    year: bigint;
    brand: string;
} {
    return {
        model: value.model,
        vehicleType: to_candid_VehicleType_n12(_uploadFile, _downloadFile, value.vehicleType),
        licensePlate: value.licensePlate,
        name: value.name,
        year: value.year,
        brand: value.brand
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: JobStatus;
    completedAt?: Timestamp;
    title?: string;
    cost?: bigint;
    description?: string;
}): {
    status: [] | [_JobStatus];
    completedAt: [] | [_Timestamp];
    title: [] | [string];
    cost: [] | [bigint];
    description: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_JobStatus_n26(_uploadFile, _downloadFile, value.status)) : candid_none(),
        completedAt: value.completedAt ? candid_some(value.completedAt) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        cost: value.cost ? candid_some(value.cost) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none()
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: MaintenanceStatus;
    completedAt?: Timestamp;
    title?: string;
    dueDate?: Timestamp;
    description?: string;
}): {
    status: [] | [_MaintenanceStatus];
    completedAt: [] | [_Timestamp];
    title: [] | [string];
    dueDate: [] | [_Timestamp];
    description: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_MaintenanceStatus_n30(_uploadFile, _downloadFile, value.status)) : candid_none(),
        completedAt: value.completedAt ? candid_some(value.completedAt) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    auto: null;
} | {
    moto: null;
} {
    return value == VehicleType.auto ? {
        auto: null
    } : value == VehicleType.moto ? {
        moto: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    pending: null;
} | {
    in_progress: null;
} | {
    completed: null;
} {
    return value == JobStatus.pending ? {
        pending: null
    } : value == JobStatus.in_progress ? {
        in_progress: null
    } : value == JobStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaintenanceStatus): {
    upcoming: null;
} | {
    completed: null;
} | {
    overdue: null;
} {
    return value == MaintenanceStatus.upcoming ? {
        upcoming: null
    } : value == MaintenanceStatus.completed ? {
        completed: null
    } : value == MaintenanceStatus.overdue ? {
        overdue: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
